name: "Deploy Bootcamp"

on: 
  push:
    branches: ["main"]

jobs:
  deploy-bootcamp:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v4
      run: echo "Hacemos pull del codigo"
      run: echo "Correr migraciones"
      run: echo "Generar binario"
      run: echo "Publicar version"